### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by maximusblade** [DraperStudio/Laravel-Reviewable#1]
Nice to have:

- List all reviewed models
- List reviewed models filtered by * 
- Remove All Reviews from Model
- Get list of reviews order by average rating?
- Get models by minimum reviews rating ?
- List users by reviewed Model
- List reviewed model by User

**Comment by DraperStudio** [comment]
The `reviewable` method returns a `morphMany` relationship so you can just call any Elouquent methods on those.

Might add helper methods one day, but not for now.
